source "https://rubygems.org"

ruby "3.3.6"

gem "rails", "~> 8.0.1"
gem "pg", "~> 1.5"
gem "puma", ">= 6.0"
gem "bootsnap", require: false

# JSON serialization
gem "jbuilder"

# CORS
gem "rack-cors"

# Pagination
gem "kaminari"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end
